# Generated by Django 4.1.7 on 2023-03-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auth_time_posts_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='time',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='time',
        ),
    ]
